### ISSUE TITLE
Support for MPTS

### ISSUE THREAD

**Issue by stilldavid** [Comcast/gots#15]
Hi gang, great work!

Do you have plans to support multi-program transport streams in the future?

**Comment by BlakeOrth** [comment]
Hi David,

At the current time all of our work deals with SPTS.  That's not to say it won't be expanded at some point in the future, but it's certainly not something we have planned on the near term horizon.  Feel free to open an issue and we might get around to it eventually.  If you're willing to sign our contributor agreement and write some code we're happy to accept pull requests!

**Comment by stilldavid** [comment]
Thanks for the quick reply.

I'm relatively new to working with transport streams, but am going to have to be doing some stuff with MPTS in the near future and this package is a great starting point. If I can get something together I'm definitely open to making a pull request.

Feel free to close this.

**Comment by BlakeOrth** [comment]
Excellent, we look forward to hearing from you in the future.  Good luck on your ventures into transport streams!  

Expanding this to support MPTS should be reasonably straight forward, with most of the work going into a full parse of the PAT.  Keeping track of which PMT and ES pids corresponds to which program is easy bookkeeping best kept to the individual user.

**Comment by stilldavid** [comment]
You were right, Blake - this was easy to implement. I need to clear it with my employer, but I'll see about making a pull request that adds support for MPTS (with working tests!)

The way I implemented it has some breaking changes - namely removing `pat.ProgramMapPid` and `pat.ProgramNumber` in favor of a single `pat.ProgramMap` that returns a `map[uint16]uint16` of the program numbers and associated PIDs.

I have some other changes, most to the example cli code, that might make it easier for other folks to get started as well.
