### ISSUE TITLE
Trying to run parsefile.go to extract information

### ISSUE THREAD

**Issue by sanilraut** [Comcast/gots#26]
1. Trying to run parsefile.go to extract information

go run parsefile.go -f wjz-200309111230-clip.ts

(0x276028,0xc82006e0a0)
Pat
    PMT PID         4720
    ProgramNumber  37976
    Number of Programs 37976
Cannot close File wjz-200309111230-clip.ts <nil>
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x10af40, 0xc82000e060)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Comcast/gots/psi.PmtAccumulatorDoneFunc(0xc820080240, 0xb8, 0xb8, 0xb8, 0x0, 0x0)
    /**_/src/github.com/Comcast/gots/psi/pmt.go:49 +0xcc
github.com/Comcast/gots/packet.(_accumulator).Add(0xc82007e080, 0xc820080180, 0xbc, 0xbc, 0xbc, 0x0, 0x0)
    /**_/src/github.com/Comcast/gots/packet/accumulator.go:77 +0x347
main.extractPmt(0x2b6348, 0xc820076008, 0x2b1270, 0x0, 0x0, 0x0, 0x0)
    /_**parsefile.go:183 +0x314
main.main()
    /***/parsefile.go:68 +0x416
exit status 2
1. Information about media used:

General
ID                                         : 1403 (0x57B)
Complete name                   : wjz-200309111230-clip.ts
Format                                  : MPEG-TS
File size                                 : 10.0 MiB
Duration                                : 4s 153ms
Start time                              : UTC 2003-09-11 16:34:33
End time                                : UTC 2003-09-11 16:34:36
Overall bit rate mode            : Constant
Overall bit rate                       : 19.4 Mbps
Movie name                            : The Young and The Restless
Law rating                               : TV-14 (D)

Video
ID                                                      : 17 (0x11)
Menu ID                                            : 1 (0x1)
Format                                              : MPEG Video
Format version                                 : Version 2
Format profile                                   : Main@High
Format settings, BVOP                     : Yes
Format settings, Matrix                     : Default
Format settings, GOP                        : M=3, N=15
Format settings, picture structure    : Frame
Codec ID                                             : 2
Duration                                              : 3s 937ms
Bit rate mode                                      : Variable
Bit rate                                                 : 18.0 Mbps
Maximum bit rate                                : 19.2 Mbps
Width                                                   : 1 920 pixels
Height                                                  : 1 080 pixels
Display aspect ratio                            : 16:9
Frame rate                                           : 29.970 (30000/1001) fps
Color space                                         : YUV
Chroma subsampling                          : 4:2:0
Bit depth                                              : 8 bits
Scan type                                             : Interlaced
Scan order                                            : Top Field First
Compression mode                              : Lossy
Bits/(Pixel*Frame)                               : 0.290
Stream size                                          : 8.47 MiB (85%)

Audio
ID                                             : 20 (0x14)
Menu ID                                   : 1 (0x1)
Format                                     : AC-3
Format/Info                              : Audio Coding 3
Mode extension                       : CM (complete main)
Format settings, Endianness  : Big
Codec ID                                  : 129
Duration                                   : 4s 128ms
Bit rate mode                           : Constant
Bit rate                                      : 384 Kbps
Channel(s)                                : 2 channels
Channel positions                     : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                                 : 31.250 fps (1536 spf)
Compression mode                   : Lossy
Delay relative to video               : -256ms
Stream size                                : 194 KiB (2%)
Language                                   : English

Text #1
ID                                           : 17 (0x11)-CC1
Menu ID                                 : 1 (0x1)
Format                                   : EIA-608
Muxing mode                         : A/53 / DTVCC Transport
Muxing mode, more info       : Muxed in Video #1
Duration                                 : 3s 937ms
Bit rate mode                         : Constant
Stream size                            : 0.00 Byte (0%)

Text #2
ID                                       : 17 (0x11)-1
Menu ID                             : 1 (0x1)
Format                                : EIA-708
Muxing mode                     : A/53 / DTVCC Transport
Muxing mode, more info   : Muxed in Video #1
Duration                             : 3s 937ms
Bit rate mode                     : Constant
Stream size                        : 0.00 Byte (0%)

Menu
ID                                       : 16 (0x10)
Menu ID                             : 1 (0x1)
Duration                             : 4s 153ms
List                                     : 17 (0x11) (MPEG Video) / 20 (0x14) (AC-3, English)
Title                                    : The Young and The Restless
Language                           :  / English
Service name                     : WJZ Digital
Service channel number    : 13-1
Service type                       : Digital television
Law rating                           : TV-14 (D)

Also how to use other options like pmt, ebp and pid. Can someone please give me an example?

**Comment by guygrigsby** [comment]
`-pmt` is a boolean flag and is enabled by default. 

`-ebp` is also boolean and it outputs info for every EBP encountered. 
Example: `go run parsefile.go -f wjz-200309111230-clip.ts -ebp`. 

`-pid` takes an integer and outputs the first packet encountered on that PID to stdout. 
Example: `go run parsefile.go -f wjz-200309111230-clip.ts -pid 1` (Assuming that PID 1 exists) 

As for the core, I can't say off hand without looking at the asset, but these numbers are certainly bogus:
ProgramNumber 37976
Number of Programs 37976

Have you tried with any other assets?

**Comment by guygrigsby** [comment]
I found the asset you are using online and figured out the issue. The asset starts with something that is not a valid TS packet. The transcoder that created it must have added some additional info at the beginning. You can get it to work if you open the file in a hex editor and delete that prefix, up until the first sync byte 0x47. 

**I will leave this open, because it might be a good idea to verify sync bytes.** @BlakeOrth What do you think?

**Comment by BlakeOrth** [comment]
I absolutely think we should verify we're synched with the stream before we attempt to parse.

**Comment by sanilraut** [comment]
Thanks @guygrigsby . Can I work on the function to find the first sync byte before parsing?

**Comment by guygrigsby** [comment]
@sanilraut Please do! Don't for get to sign and send us this https://github.com/Comcast/gots/blob/master/CLA.pdf.
