### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by guygrigsby** [Comcast/gots#29]
#28 added MPTS support, but we kept two methods, `ProgramMapPid` and `ProgramNumber ` for compatibility. We need to remove those after sufficient time is given to update projects that depend on `gots`.

**Comment by BlakeOrth** [comment]
#36 idiomaticized a constant (`MAX_PTS`) that will also need to be removed in a future version.

**Comment by guygrigsby** [comment]
@BlakeOrth I would like to make these changes this week. Do you have any objections?

**Comment by BlakeOrth** [comment]
It's not going to have any impact on us anytime soon, so no objections here.
