### ISSUE TITLE
Move CLI helpers into package(s) to be part of API

### ISSUE THREAD

**Issue by davemt** [Comcast/gots#30]
There are a few helpers in the `parsefile` cli example that would be useful if made available as part of package(s) rather than just the cli program. For example, `sync` function, and functions to read PAT/PMT. I think they are general enough (with a couple of tweaks) that it could save from people needing to repeat those bits of code.

**Comment by guygrigsby** [comment]
I think that this makes sense. I'll take a look at it when I can. If anyone else is interested in this, go for it. Don't wait on me.
