### ISSUE TITLE
PSI interface and PMT parser assume single "Program Map" section

### ISSUE THREAD

**Issue by tmm1** [Comcast/gots#74]
`psi.TableID()` and `psi.SectionLength()` assume that each PSI packet only contains one section, but in fact there can be multiple. See for instance https://en.wikipedia.org/wiki/Program-specific_information#Table_Sections, which states that after the pointer field, section headers are "repeated until the end of the TS packet payload".

Specifically, on streams from Comcast and other cable providers, tables 0xc0 and 0xc1 may be present in the PMT pid's packets (see "SCTE specific tables" on https://en.wikipedia.org/wiki/Program-specific_information#Table_Identifiers).

I'd like to open a PR to fix this, but I'm curious if I can change the implementations of `TableID` and `SectionLength`, or if you would prefer to keep them as-is for backwards compatibility for any existing users of the public API?

**Comment by BlakeOrth** [comment]
Ideally we'd like to keep the public API backwards compatible.  Considering those functions both take a simple byte slice and have a simple return type I'd think there would be a clean implementation without changing them.

Thanks for your interest and the future PR!

**Comment by tmm1** [comment]
Thanks. I came to the same conclusion, and left the public API in-tact in #75
