### ISSUE TITLE
packet: propose Packet be changed to [188]byte

### ISSUE THREAD

**Issue by kortschak** [Comcast/gots#83]
At the moment, a `packet.Packet` is a `[]byte` and in many places it's passed as a point to this. It's not clear to me why that is since the type is already a point to the backing array. Removing the pointer would be one option, but given that the packet size is fixed at 188 bytes, making it a `[188]byte` and passing pointers to that makes more sense. Of course this breaks users, so feel free to ignore this - it just seems weird and incurs a double dereference unnecessarily.

**Comment by guygrigsby** [comment]
We did think about this when designing the library and decided to go with slices because go is really made to work with slices rather than directly with arrays. It is unfortunate that we are using pointers to slices. We should probably not be doing that. Leaving this open because of that and for any other discussion surrounding the `[188]byte` idea.

**Comment by BlakeOrth** [comment]
I'm going to add my support for slices (more idiomatic Go), but refactor the pointers to slices, as that's a useless construct.

**Comment by kortschak** [comment]
> because go is really made to work with slices rather than directly with arrays

I'm not entirely sure I understand the basis for this comment. Go has a variety of types and the types serve there purposes. Slices are a perfect fit for things that are variable length and mutable, strings are variable length and immutable, arrays are non-variable length and mutable (the 4 position is missing). All of the things that you might want to do with a fixed-size packet type are readily doable with an array. I'll send a PR - not for merging, but for illustration - that shows this.

**Comment by kortschak** [comment]
Closed by #84.
